language: ruby

rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
  - 2.0
  - 1.9.3
  - ruby-head
  - jruby-1.7
  - jruby-9.1.2.0
  - jruby-9.0.5.0
  - jruby-19mode
  - jruby-head

gemfile:
  - Gemfile

bundler_args: --path vendor/bundle

sudo: false

before_script:
  - bundle exec rake travis:before -t

script: bundle exec rake travis

after_script:
  - bundle exec rake travis:after -t

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

notifications:
  email:
    recipients:
      - austin@rubyforge.org
    on_success: change
    on_failure: always
